Repository chaos-genius/chaos_genius, pull requests merged in 2022-08, with the labels that each got.

#1068 fix: check dashboard/datasource active in filter options
  chaos_genius/controllers/dashboard_controller.py
  chaos_genius/controllers/data_source_controller.py
Labels: 🐛 bug, 🛠️ backend

#1070 added searchable dimensional and subdimensional value options
  frontend/src/components/Anomaly/index.jsx
Labels: 🖥️ frontend

#1072 fix: check dashboard/datasource active in filter options
  chaos_genius/controllers/dashboard_controller.py
  chaos_genius/controllers/data_source_controller.py
Labels: 🐛 bug, 🛠️ backend

#1069 feat(subdim-filter): sort dimension and value lists
  chaos_genius/views/anomaly_data_view.py
Labels: 🛠️ backend

#1067 Removed xAxis legend of KPI summary chart
  frontend/src/components/DashboardGraph/index.jsx
Labels: 🖥️ frontend

#1073 Disable analytics endpoint
  chaos_genius/commands.py
  chaos_genius/jobs/analytics_scheduler.py
  chaos_genius/views/anomaly_data_view.py
  chaos_genius/views/download_view.py
  chaos_genius/views/kpi_view.py
  tests/test_analytics_scheduler.py
Labels: 🛠️ backend

#1077 fix(anomaly): ensure correct data types
  chaos_genius/core/anomaly/processor.py
Labels: 🐛 bug, 🛠️ backend

#1078 fix(docker): add analytics params to alerts worker
  docker-compose.dev-thirdparty.yml
  docker-compose.dev.yml
  docker-compose.fluentd.yml
  docker-compose.latest-thirdparty.yml
  docker-compose.latest.yml
  docker-compose.thirdparty.yml
  docker-compose.yml
Labels: 🏗️ infrastructure

#1080 Dimension and subdimensional options should be searchable
  frontend/src/components/Anomaly/index.jsx
Labels: 🖥️ frontend

#1079 fix: check dashboard/datasource active in filter options
  chaos_genius/controllers/dashboard_controller.py
  chaos_genius/controllers/data_source_controller.py
Labels: 🐛 bug, 🛠️ backend

#1081 called all alerts API when alerts are deleted
  frontend/src/containers/Alerts/index.jsx
Labels: 🖥️ frontend

#1082 fix(anomaly): convert slack into hourly value for hourly KPIs
  chaos_genius/core/anomaly/controller.py
Labels: 🐛 bug, 🛠️ backend

#1092 changed sidebar support text and icon
  frontend/src/assets/images/sidebar/support_slack.svg
  frontend/src/components/Sidebar/index.jsx
Labels: 🖥️ frontend

#1090 Feature/clickhouse connector
  chaos_genius/connectors/__init__.py
  chaos_genius/connectors/clickhouse.py
  chaos_genius/third_party/data_connection_config.json
  chaos_genius/third_party/integration_server_config.py
  chaos_genius/utils/metadata_api_config.py
  requirements/prod.txt
Labels: 🔗 connectors, :paperclip: needs docs update
